# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-08 10:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isdeleted', models.BooleanField(default=False)),
                ('isdisabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DevSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devskillsid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeid', models.IntegerField()),
                ('joiningdate', models.DateField(max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('isdeleted', models.BooleanField(default=False)),
                ('isdisabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceMastersId', models.IntegerField()),
                ('invoicedate', models.DateField()),
                ('invoiceamount', models.IntegerField()),
                ('services', models.CharField(max_length=500)),
                ('tax', models.IntegerField()),
                ('discount', models.CharField(max_length=50)),
                ('workhours', models.IntegerField()),
                ('hourlyrate', models.IntegerField()),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.Client')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('contactNo', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('dateOfBirth', models.DateField()),
                ('spouseName', models.CharField(max_length=20)),
                ('spouseDOB', models.DateField()),
                ('anniversary', models.DateField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=1500)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('cost', models.IntegerField()),
                ('project_type', models.CharField(choices=[('1', 'webforms'), ('2', 'winforms'), ('3', 'Native mobile APPS'), ('4', 'Hybrid mobile APPS')], max_length=1)),
                ('document', models.FileField(upload_to='')),
                ('isdeleted', models.BooleanField(default=False)),
                ('isdisabled', models.BooleanField(default=False)),
                ('is_favorite', models.BooleanField(default=False)),
                ('clientid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.Client', verbose_name='Client')),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.Employee', verbose_name='Project Resource')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectTeamId', models.IntegerField()),
                ('employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.Employee')),
                ('projectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.Project')),
            ],
        ),
        migrations.CreateModel(
            name='StatusReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusreport_title', models.CharField(max_length=50)),
                ('report', models.TextField(max_length=1500)),
                ('reportdate', models.DateTimeField()),
                ('timedurfrom', models.TimeField(verbose_name='Duration from-')),
                ('timedurto', models.TimeField(verbose_name='To:')),
                ('is_favorite', models.BooleanField(default=False)),
                ('projectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.Project', verbose_name='project')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('techname', models.CharField(max_length=20)),
                ('isdeleted', models.BooleanField(default=False)),
                ('isdisabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='blazon.Technologies'),
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='projectid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.Project'),
        ),
        migrations.AddField(
            model_name='employee',
            name='PersonalDetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.PersonalDetail'),
        ),
        migrations.AddField(
            model_name='devskill',
            name='employeeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.Employee'),
        ),
        migrations.AddField(
            model_name='devskill',
            name='techid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.Technologies'),
        ),
        migrations.AddField(
            model_name='client',
            name='personaldetail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blazon.PersonalDetail'),
        ),
    ]
