# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-08 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blazon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectteam',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
