# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-06-08 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blazon', '0002_projectteam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='devskill',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
