# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-11 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailtemplate',
            name='from_email',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='emailtemplate',
            name='to_email',
        ),
    ]
