# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-11 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0002_auto_20180911_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
