# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-11 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0003_emailtemplate_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailtemplate',
            old_name='document',
            new_name='logo',
        ),
    ]
