# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-09-11 09:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mailapp', '0004_auto_20180911_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 11, 9, 25, 8, 69578, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
